### PR TITLE
Dual fuel heat pumps

### PR DESCRIPTION
**Pull request by shorowit**
Add support for dual fuel heat pumps (with an optional switchover temperature).

### CODE REVIEW

**Comment by jonwinkler** [comment]
@shorowit Since we agreed to hold off on dual fuel GSHPs, do you want to revise EPvalidator and test files?

**Comment by shorowit** [comment]
I ran tests for all system types and timeseries results looked good. Code changes look great, especially creating a method for applying the supplemental coil and clearly differentiating between min compressor temperature and max supplemental temperature. Nice work, @jonwinkler.

I'm going to work on incorporating this in ERI (which may require some additional changes to get loads seen by the heat pump separate from the backup system) and will merge when it's all done.

**Comment by shorowit** [comment]
@jonwinkler Shouldn't the DFHP supplemental coil be autosized differently than the typical ASHP supplemental coil? I.e., using the switchover temperature?

**Comment by jonwinkler** [comment]
@shorowit According the Manual S (version 1; I'm not sure where my v2 is), dual fuel heat pumps should be sized based on the cooling load, which is the same guidance for typical ASHPs. But we're sizing typical ASHPs using the ERI guidance to size on max cooling or heating load. The max heating load for a dual fuel heat pump would occur at the switchover temperature, so unless ERI states otherwise perhaps we should be using the switchover temp.

**Comment by shorowit** [comment]
This is tested and good to go. Thanks, @jonwinkler!

**Pull request merged**
