### PR TITLE
BuildResidentialHPXML: Check attic floor insulation assembly R-value

### LINKED ISSUE #1295: BuildResidentialHPXML: Check attic floor insulation assembly R-value
We are not gracefully handling an error (divide by zero) when there is an attic and `floor.insulation_assembly_r_value=0` here: https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L873

This can happen since we are applying defaults from `BuildResidentialHPXML` but not necessarily first applying validation on the HPXML file.

Should resstock `apply_validation=true` from BuildExistingModel?

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1295.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Schematron validator (`EPvalidator.xml`) has been updated
- [ ] Sample files have been added/updated (via `tasks.rb`)
- [x] Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests` and/or `workflow/tests/hpxml_translator_test.rb`)
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

**Comment by shorowit** [comment]
The change is of course fine, but there are probably a hundred ways that similar errors can occur, and this only catches one of them. And it duplicates error-checking that occurs in the Schema/Schematron documents.

My inclination is to go a different path:
1. Force `apply_validation` to be true when `apply_defaults` is true. (Update the `apply_defaults` arg description to make this clear.)
2. Apply validation _before_ the defaults are applied, and exit the measure prematurely if the validation is unsuccessful. (We could technically apply validation twice, once before the defaulting occurs and again after, but we'd take a hit on performance twice for doing that. I think we should assume that the defaulting code will not somehow produce an invalid HPXML.)

**Comment by joseph-robertson** [comment]
I had thought about essentially doing (1) (i.e., set `apply_validation=true` from BuildExistingModel) - but was worried about a performance hit in the context of resstock. I suppose we could time it using ci...

**Comment by shorowit** [comment]
If validation is enabled in the BuildResHPXML measure, it could then be turned off in the HPXMLtoOS measure ([here](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/measure.rb#L58)).

**Comment by shorowit** [comment]
(So there would be no net performance hit in ResStock.)

**Comment by shorowit** [comment]
@joseph-robertson This can be closed now, right?

**Comment by joseph-robertson** [comment]
Went with this approach instead: https://github.com/NREL/OpenStudio-HPXML/pull/1298.

**Pull request closed without merging**
