### PR TITLE
Schedule:File relative paths

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Test https://github.com/NREL/OpenStudio/pull/4879.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] ~Schematron validator (`EPvalidator.xml`) has been updated~
- [ ] ~Sample files have been added/updated (via `tasks.rb`)~
- [ ] ~Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests` and/or `workflow/tests/hpxml_translator_test.rb`)~
- [ ] ~Documentation has been updated~
- [ ] ~Changelog has been updated~
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

**Comment by shorowit** [comment]
@joseph-robertson Maybe I just don't follow what you're doing, but I wouldn't expect any changes are needed on the OS-HPXML side. OS-HPXML is already creating an OSM that has relative paths in it, they just need to be preserved in the IDF. It shouldn't matter what working directory is being used.

**Comment by shorowit** [comment]
Okay, I partly take that back. OS-HPXML is not currently creating an OSM with a relative path, but doing so just means changing [this line](https://github.com/NREL/OpenStudio-HPXML/blob/4e5996a2318b8d22440b4c08f14f02887b03e7b4/HPXMLtoOpenStudio/resources/schedules.rb#L1509) to be a relative path. Changing the working directory is risky and should be avoided.

**Comment by joseph-robertson** [comment]
I was trying to change the `output_dir` from abs to rel (which, correct, I'm now realizing I just need to make the `@output_schedules_path` relative). But where does the working directory get changed?

On a related note, this gets tricky. We need to pass a valid relative (to current working directory) path into `ScheduleFile`, but `ExternalFile` needs to be written with just the basename of that relative path. Right? Or can OSM's ExternalFile "File Name" be the original rel path, and it's up to FT to write out just the basename?

**Comment by joseph-robertson** [comment]
I think we want both the OSM and IDF to have relative paths to the schedule file (alongside the OSM and IDF)?

**Comment by joseph-robertson** [comment]
@shorowit

Not exactly sure how this should be reviewed. Test locally using installer at the bottom of https://github.com/NREL/OpenStudio/pull/4879? Request that a docker image be created so CI can handle it?

**Comment by shorowit** [comment]
@joseph-robertson Are you trying to get https://github.com/NREL/OpenStudio/pull/4879 into OS 3.7, or is it for the following release?

**Comment by joseph-robertson** [comment]
> @joseph-robertson Are you trying to get [NREL/OpenStudio#4879](https://github.com/NREL/OpenStudio/pull/4879) into OS 3.7, or is it for the following release?

@shorowit Sounds like OpenStudio will have a v3.7.0-rc2. And because https://github.com/NREL/OpenStudio/pull/4879 seems to be working, I think it makes sense to try getting it in this upcoming release.

**Comment by shorowit** [comment]
Got it. If you're happy with how things are working, then it sounds like you can proceed w/ getting the OS PR merged for rc2. I assume you don't need the CI tests here to pass for that to happen. When rc2 is available, we can update the CI for this PR.

**Review by shorowit — APPROVED** [review]
Looks good. Will merge once the CI comes back green.

**Pull request merged**
