### PR TITLE
Update hot water end uses for operational calculations

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

For operational calculations (where `NumberofResidents` is provided), we now directly use equations from the [FSEC paper](http://www.fsec.ucf.edu/en/publications/pdf/fsec-pf-464-15.pdf) that are a function of number of occupants.

## Checklist

Not all may apply:

- [ ] Schematron validator (`EPvalidator.xml`) has been updated
- [ ] Sample files have been added/updated (`openstudio tasks.rb update_hpxmls`)
- [x] Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests/test*.rb` and/or `workflow/tests/test*.rb`)
- [x] Documentation has been updated
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

**Comment by shorowit** [comment]
This is ready for testing by @jmaguire1.

**Review by jmaguire1 — COMMENTED** [review]
This all looks good to me. I'm assuming you'd like to wait until I've looked at the ResStock results later this week before we merge?

**Comment by shorowit** [comment]
> This all looks good to me. I'm assuming you'd like to wait until I've looked at the ResStock results later this week before we merge?

Thanks @jmaguire1. Yes, there's no rush so I will wait on further testing.

**Comment by shorowit** [comment]
ORNL confirmed the results look good for WAP, going to merge if the CI comes back green. If ResStock testing identifies any problems, we can address them in a subsequent PR.

**Pull request merged**
