### PR TITLE
ViewFactor approach improvement

### PR DESCRIPTION
**Pull request by yzhou601**
## Pull Request Description

To improve view factor approach implemented for single conditioned space workflow.

## Checklist

Not all may apply:

- [ ] EPvalidator.rb has been updated
- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI

### CODE REVIEW

**Comment by yzhou601** [comment]
One error check added here. Fixed a "subsurface in basement" issue, not captured in test cases. So no CI diff here.

**Comment by shorowit** [comment]
Were you going to add a check that the .err file doesn't have warnings like "Warning ** FixViewFactors: View factors not complete"? Similar to [this check](https://github.com/NREL/OpenStudio-HPXML/blob/master/workflow/tests/hpxml_translator_test.rb#L617-L623).

**Comment by yzhou601** [comment]
> Were you going to add a check that the .err file doesn't have warnings like "Warning ** FixViewFactors: View factors not complete"? Similar to [this check](https://github.com/NREL/OpenStudio-HPXML/blob/master/workflow/tests/hpxml_translator_test.rb#L617-L623).

Sure I can. I thought we came to the conclusion to add error check in workflow. 
I will also add that one for testing files.

**Comment by shorowit** [comment]
Thanks. Seems best to have both!

**Comment by shorowit** [comment]
Confirmed that the basement window test file produces a change. All other files are unchanged.

**Pull request merged**
