### PR TITLE
Set schedule file temp directory

### LINKED ISSUE #1070: Schedule file temp directory running out of memory on Eagle
This is in the context of running ResStock on Eagle. The schedule file created in a temporary directory [here](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedules.rb#L1157) is being written by default as `/tmp/schedule_foo.csv`. However on an Eagle node, the `/tmp` directory is a 150 MB RAM disk.

```
Filesystem                                                                 Size  Used Avail Use% Mounted on
devtmpfs                                                                    47G     0   47G   0% /dev
tmpfs                                                                       47G     0   47G   0% /dev/shm
tmpfs                                                                       47G  3.4G   44G   8% /run
tmpfs                                                                       47G  3.2G   44G   7% /
tmpfs                                                                       47G     0   47G   0% /sys/fs/cgroup
tmpfs                                                                      150M     0  150M   0% /tmp
/dev/sda1                                                                  932G   33M  932G   1% /tmp/scratch
lead-eth:/var/lib/sgi/per-host/ice-centos7.7-slurm/4/i7n35/var/log/memlog  2.0G   72M  2.0G   4% /var/log/memlog
10.148.67.8:/home                                                          182T   48T  135T  27% /home
10.148.67.8:/nopt                                                          182T   48T  135T  27% /nopt
10.148.66.1@o2ib:10.148.66.2@o2ib:/eaglefs                                  18P   14P  3.5P  80% /lustre/eaglefs
```

It looks like in ruby you can tell the [`Tempfile.new` constructor](https://ruby-doc.org/stdlib-2.5.3/libdoc/tempfile/rdoc/Tempfile.html#method-c-new) a directory in which to place the temp file. You could detect whether you're on Eagle with the `LOCAL_SCRATCH` environment variable, which contains the path where a local 1TB local drive is stored that gets erased at the end of the job (always `/tmp/scratch`).

Another option would be to just store the schedule file in the run directory. We already store the openstudio run directory under `/tmp/scratch`. I'm not clear why this schedule file is being written as a temp file, but I'm sure you have reasons. 

@shorowit @joseph-robertson @mnblonsky @jmaguire1

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Closes #1070.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Schematron validator (`EPvalidator.xml`) has been updated
- [ ] Sample files have been added/updated (via `tasks.rb`)
- [ ] Unit tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests`)
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] Checked the code coverage report on CI
- [ ] No unexpected changes to simulation results of sample files

### CODE REVIEW

**Review by shorowit — APPROVED** [review]

**Comment by mnblonsky** [comment]
Hi all,
I am still getting an error saying there is limited space in /tmp, it looks like the temp folder isn't getting updated. From run.log file when running `buildstock_eagle -m`:
`[12:07:49.940099 ERROR] No space left on device @ fptr_finalize_flush - /tmp/schedules20220518-35595-18wv8k.csv`

I am using the develop branch of ResStock and buildstockbatch. I can see the changes you made, so it seems like I don't have LOCAL_SCRATCH variable in my environment within the job. Is that possible? Do you think it's necessary to include LOCAL_SCRATCH in the variables you pass though in eagle.py?

**Comment by nmerket** [comment]
Doh! This is running in a singularity container, isn't it?

**Comment by mnblonsky** [comment]
Yes. I think so

**Comment by nmerket** [comment]
That means this is seeing a different filesystem than the one on the node. This is probably a buildstockbatch issue more than anything. Sounds like we need to mount `/tmp/scratch` into the container.

**Pull request merged**
