### PR TITLE
Replaces `UseMaxLoadForHeatPumps` option with `HeatPumpSizingMethodology`

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

Addresses #1011. 

**Breaking change**: Replaces the `UseMaxLoadForHeatPumps` sizing option with `HeatPumpSizingMethodology`, which has three choices:
  - `ACCA`: nominal capacity sized per ACCA Manual J/S based on cooling design loads, with some oversizing allowances for larger heating design loads.
  - `HERS` (default): nominal capacity sized equal to the larger of heating/cooling design loads.
  - `MaxLoad`: nominal capacity sized based on the larger of heating/cooling design loads, while taking into account the heat pump's capacity retention at the design temperature.

Defaulting to HERS results in identical default behavior, in that it matches the previous `UseMaxLoadForHeatPumps` sizing option.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [x] ~Schematron validator (`EPvalidator.xml`) has been updated~
- [x] ~Sample files have been added/updated (via `tasks.rb`)~
- [x] ~Unit tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests`)~
- [x] ~Documentation has been updated~
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] Checked the code coverage report on CI
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

**Comment by whiphi92** [comment]
Do we have extended documentation about each `HeatPumpSizingMethodology` argument? I can imagine this would be very helpful in the long-term when some of us have forgotten the details of each option, unless others think the information in this issue is sufficient. Tagging @ejhw in case he has specific opinions on this.

**Comment by shorowit** [comment]
@whiphi92 The same information is available in the [OS-HPXML documentation for HVAC sizing controls](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-hvac-sizing-control). Let me know if you think additional information or changes are needed.

**Comment by ejhw** [comment]
The only thing that might be worth adding is the specifics of "oversizing allowances for larger heating design loads", i.e., X% oversizing allowed for 2-stage, Y% for variable-speed, and maybe mentioning why ACCA Manual S doesn't let you go further, particularly for single-stage equipment (oversizing reduces dehum. capacity).

**Comment by whiphi92** [comment]
I agree with Eric, with one more addition of clarity. What does "while taking into account the heat pump’s capacity retention at the design temperature" mean and how is that different from HERS?

**Comment by shorowit** [comment]
@ejhw It's not simply X% and Y%, in some cases it's an absolute oversizing limit in Btu/hr. It would be complicated to try to describe all the nuances of the ACCA methodology and the assumed justification for it. The language states that there are oversizing allowances; if someone wants to understand what/why they are, they should consult the ACCA Manual.

**Comment by ejhw** [comment]
@shorowit Is it more than just [this code](https://github.com/NREL/OpenStudio-HPXML/blob/7be925f0e28447e954336a7ecbb0bb81c1c9a9ba/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L2368-L2371)?

**Comment by shorowit** [comment]
@ejhw Yes: https://github.com/NREL/OpenStudio-HPXML/blob/7be925f0e28447e954336a7ecbb0bb81c1c9a9ba/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L2009-L2015

**Pull request merged**
