### PR TITLE
Fixes BuildResHPXML measure ducts CFA served when load fraction served < 1

### LINKED ISSUE #1440: BuildResHPXML measure: Update ducts CFA served when load fraction served < 1
Currently the air distribution system's CFA served defaults to the entire home's CFA:
https://github.com/NREL/OpenStudio-HPXML/blob/4f093def65dd438569b5829529dd75ffe7a48db9/BuildResidentialHPXML/measure.rb#L5111-L5114

That's usually right. But if the ducted HVAC system only serves a fraction of the load (e.g., because there is a secondary system), then the CFA served should be similarly reduced. Perhaps the CFA served should equal `CFA x max(fraction_heat_load_served, fraction_cool_load_served)`?

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

Fixes #1440.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [x] ~Schematron validator (`EPvalidator.xml`) has been updated~
- [x] Sample files have been added/updated (via `tasks.rb`)
- [x] ~Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests` and/or `workflow/tests/hpxml_translator_test.rb`)~
- [x] ~Documentation has been updated~
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

**Comment by joseph-robertson** [comment]
Doesn't appear that any simulation results of sample files are changed. Should a test be created (e.g., a new sample file)?

**Comment by shorowit** [comment]
For the new sample file, which has a non-ducted cooling system and a ducted heating system that meets 75% of the heating load (with a fireplace meeting the other 25%), the HPXML file has an air distribution w/ CFA served = 2025 ft2:

https://github.com/NREL/OpenStudio-HPXML/blob/78bc6c366cd1580c01235764b4b06185c13aedf5/workflow/sample_files/base-hvac-ducts-defaults.xml#L404

Prior to this fix, the HPXML file would have an air distribution w/ CFA served = 2700 ft2.

**Comment by shorowit** [comment]
Results in https://github.com/NREL/resstock/pull/1108 also look good.

**Comment by joseph-robertson** [comment]
> Yes, it's still a draft PR and needs a test.

Sorry! Wasn't trying to be pushy - just something I noticed so I threw in a comment.

**Comment by joseph-robertson** [comment]
@shorowit I found an issue with this implementation. When, for example, a heat pump has separate backup, [this line](https://github.com/NREL/OpenStudio-HPXML/blob/master/BuildResidentialHPXML/measure.rb#L5116) throws "Measure Failed with Error: comparison of NilClass with 0.0 failed". I believe this is because `fraction_heat_load_served` gets set to `nil` for a "secondary heating system" that is designated to be separate backup to the heat pump: https://github.com/NREL/OpenStudio-HPXML/blob/master/BuildResidentialHPXML/measure.rb#L4964-L4966.

**Comment by shorowit** [comment]
> @shorowit I found an issue with this implementation. When, for example, a heat pump has separate backup, [this line](https://github.com/NREL/OpenStudio-HPXML/blob/master/BuildResidentialHPXML/measure.rb#L5116) throws "Measure Failed with Error: comparison of NilClass with 0.0 failed". I believe this is because `fraction_heat_load_served` gets set to `nil` for a "secondary heating system" that is designated to be separate backup to the heat pump: https://github.com/NREL/OpenStudio-HPXML/blob/master/BuildResidentialHPXML/measure.rb#L4964-L4966.

Can you create a sample file that demonstrates this? You could work off the sample file I added in this PR.

**Comment by joseph-robertson** [comment]
> > @shorowit I found an issue with this implementation. When, for example, a heat pump has separate backup, [this line](https://github.com/NREL/OpenStudio-HPXML/blob/master/BuildResidentialHPXML/measure.rb#L5116) throws "Measure Failed with Error: comparison of NilClass with 0.0 failed". I believe this is because `fraction_heat_load_served` gets set to `nil` for a "secondary heating system" that is designated to be separate backup to the heat pump: https://github.com/NREL/OpenStudio-HPXML/blob/master/BuildResidentialHPXML/measure.rb#L4964-L4966.
> 
> Can you create a sample file that demonstrates this? You could work off the sample file I added in this PR.

https://github.com/NREL/OpenStudio-HPXML/pull/1448

**Pull request merged**
