### PR TITLE
BuildResidentialHPXML measure: Additional plug loads multipliers

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

Add:
* `plug_loads_television_usage_multiplier_2` (default=1)
* `plug_loads_other_usage_multiplier_2` (default=1)
* `plug_loads_well_pump_usage_multiplier_2` (default=1)
* `plug_loads_vehicle_usage_multiplier_2` (default=1)

These get multiplied by the first usage multiplier.

Also adds test osw files:
* `extra-plug-loads-additional-multipliers.osw`
  * `plug_loads_television_usage_multiplier_2=1.5`
  * `plug_loads_other_usage_multiplier_2=1.5`
  * `plug_loads_well_pump_usage_multiplier_2=1.5`
  * `plug_loads_vehicle_usage_multiplier_2=1.5`
* `invalid_files/multipliers-without-plug-loads.osw`
  * `plug_loads_television_annual_kwh=0`
  * `plug_loads_television_usage_multiplier=1.5`
  * `plug_loads_television_usage_multiplier_2=1.5`
  * `plug_loads_other_annual_kwh=0`
  * `plug_loads_other_usage_multiplier=1.5`
  * `plug_loads_other_usage_multiplier_2=1.5`
  * `plug_loads_well_pump_present=false`
  * `plug_loads_well_pump_usage_multiplier=1.5`
  * `plug_loads_well_pump_usage_multiplier_2=1.5`
  * `plug_loads_vehicle_present=false`
  * `plug_loads_vehicle_usage_multiplier=1.5`
  * `plug_loads_vehicle_usage_multiplier_2=1.5`

## Checklist

Not all may apply:

- [ ] EPvalidator.xml has been updated
- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected regression test changes on CI

### CODE REVIEW

**Comment by shorowit** [comment]
No one outside of ResStock will know what these mean. Can we just use more generic argument names, like "Television Usage Multiplier 2" and "Other Diversity Multiplier 2"?

**Comment by joseph-robertson** [comment]
> No one outside of ResStock will know what these mean. Can we just use more generic argument names, like "Television Usage Multiplier 2" and "Other Diversity Multiplier 2"?

"Other Diversity" or "Other Usage"?

**Comment by shorowit** [comment]
Oops. Other usage.

**Comment by joseph-robertson** [comment]
Good idea. Similarly I'll add in additional multiplier arguments for well pump and electric vehicle, too,

**Pull request merged**
