### PR TITLE
Change combi system setpoint

### PR DESCRIPTION
**Pull request by yzhou601**
Lower a little bit combi system setpoint for consistency with other systems.

### CODE REVIEW

**Comment by yzhou601** [comment]
Btw this issue existed for both previous EMS approach and updated EMS approach in this PR. And the current branch showed a smaller discrepancy than before.

**Comment by yzhou601** [comment]
Need to revisit the above energy issue discovered when implementing setpoint change. 
But the setpoint  changes seemed to be working better than before, @shorowit do you want to separate them and merge this first or wait until both solved?

**Comment by shorowit** [comment]
Let's separate them. If you are happy with this, please assign me as reviewer.

**Comment by shorowit** [comment]
Hot water volumes look reasonable. Good to go.

**Pull request merged**
